# Generated by Django 5.1.3 on 2024-11-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=255, null=True),
        ),
    ]
